# Generated by Django 3.0.8 on 2020-09-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200925_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='c_id',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='c_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='customer.CustomerRegistrationModel'),
        ),
    ]
