# Generated by Django 3.0.8 on 2020-09-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200925_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitemmodel',
            old_name='statu',
            new_name='status',
        ),
    ]
